### ISSUE TITLE
Github and Gerrit repo have diverged

### ISSUE THREAD

**Issue by tgr** [WikibaseSolutions/WSOAuth#5]
Just as a heads-up (since I think this is a problem with Wikimedia tooling), I have filed [T263955](https://phabricator.wikimedia.org/T263955) about how Wikimedia's code review platform seems to have unintentionally forked the extension.

**Comment by 26** [comment]
I have replied to the Phabricator task [here](https://phabricator.wikimedia.org/T263955#6496927). I will close this issue on GitHub now.

**Comment by TrueBrain** [comment]
Worth mentioning: without commit https://github.com/WikibaseSolutions/WSOAuth/commit/8a91dff31fe86e7b3ffef35e68907bddc148a5e4 that is only in the Github repo, I could not get the extension to work. Took me a while to figure out that the release on https://www.mediawiki.org/wiki/Extension:WSOAuth wasn't going to work. With a `git clone` from this repository it does work :)

**Comment by 26** [comment]
I have changed the download link on the extension page to the GitHub download until this task has been resolved.
