### ISSUE TITLE
"Remember me" flag not set by MediaWiki provider

### ISSUE THREAD

**Issue by tgr** [WikibaseSolutions/WSOAuth#8]
When logging in via the MediaWiki provider, the "remember me" flag (the equivalent of the ["Keep me logged in"](https://www.mediawiki.org/wiki/%22Keep_me_logged_in%22_extended_to_one_year) checkbox on the user interface) is not set and thus the user token cookie is not set, making user sessions short-lived.

**Comment by tgr** [comment]
The MediaWiki provider being what I experienced this with, but since this is about the flag on the local wiki, not the remote one, it probably affects all providers.

**Comment by 26** [comment]
Shouldn't this be handled by PluggableAuth?

**Comment by tgr** [comment]
I suppose it should be. Filed as [T265263](https://phabricator.wikimedia.org/T265263).
